# Change baseurl before deploy
baseurl = "https://blog.thgirls.yt"
languageCode = "en-us"
title = "Tokyo Hacker Girls"

# Theme i18n support
# Available values: en, fr, id, ja, ko, pt-br, zh-cn, zh-tw, es, de, nl, it, th, el, uk, ar
defaultContentLanguage = "en"

# Set hasCJKLanguage to true if DefaultContentLanguage is in [zh-cn ja ko]
# This will make .Summary and .WordCount behave correctly for CJK languages.
hasCJKLanguage = false

# Change it to your Disqus shortname before using
disqusShortname = "tokyo-hacker-girls"

pluralizeListTitles = false

[pagination]
pagerSize = 5

[taxonomies]
category = "categories"
tag = "tags"
artist = "artist"
"art tag" = "art tags"

[[module.mounts]]
source = 'content'
target = 'content'

# Clone artwork subtree as zh-cn since it has no content, only front matter
[[module.mounts]]
source = 'content/artwork'
target = 'content/artwork'
lang = 'zh-cn'

# Art tags & artwork share a layout
[[module.mounts]]
source = 'layouts'
target = 'layouts'

# Art tags & artwork share a layout
[[module.mounts]]
source = 'layouts/artwork'
target = 'layouts/art-tags'
