# Rename this file to languages.toml to enable multilingual support
[en]
languageName = "English"
languagedirection = "ltr"
title = "Tokyo Hacker Girls"
weight = 1

[zh-cn]
languageName = "简体中文"
languagedirection = "ltr"
title = "东京黑客少女"
weight = 1
